id: bdd_veh_eval_pdvcl

vocab_size: 2448
dict_file: /home/do868987/nlp_research/vocabulary/vocabulary_bdd_vehicle_wc1.json

visual_feature_type: clip
visual_feature_folder: '/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/bdd_test_feature'

feature_dim: 768
invalid_video_json: []
train_proposal_file: data/generated_proposals/dbg_trainval_top100.json
eval_proposal_file: data/generated_proposals/dbg_trainval_top100.json


gt_file_for_eval: ['/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/eval_bdd_view.json', '/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/eval_bdd_view.json']
gt_file_for_auc: '/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/eval_bdd_view.json'
gt_file_for_para_eval: ['/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/eval_entities_bdd_view.json', '/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/eval_entities_bdd_view.json']
train_caption_file: '/home/do868987/nlp_research/VidChapters/PDVC/data/bdd_all_trimmed/captiondata/train_bdd_view.json'
val_caption_file: '/data/dwang/Submission_AICityChallenge24/WTS_DATASET_PUBLIC_TEST/eval_bdd_view.json'


train_proposal_type: gt
gt_proposal_sample_num: 30
sample_method: nearest

batch_size: 4
lr: 0.001
learning_rate_decay_start: 10
learning_rate_decay_every: 10
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
save_all_checkpoint: 0
save_checkpoint_every: 10

num_queries: 10 
dec_layers: 2 
enc_layers: 2  
transformer_ff_dim: 512 
transformer_dropout_prob: 0.1
frame_embedding_num: 100
caption_decoder_type: light
att_hid_size: 0

with_box_refine: 1

fix_xcw: 1
set_cost_caption: 0
set_cost_giou: 4
set_cost_bbox: 0
set_cost_class: 2
caption_loss_coef: 2
giou_loss_coef: 4
bbox_loss_coef: 0
cls_loss_coef: 2
count_loss_coef: 0.5
max_eseq_length: 10
lloss_cross_entropy: 0
lloss_focal_loss: 0
lloss_gau_mask: 1

batch_size_for_eval: 1
max_caption_len: 300
max_eseq_length: 10


num_layers: 2
min_epoch_when_save: 0
